/*
 * Keep Charged
 *
 * API documentation
 *
 * API version: 0.0.1 beta
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Default error object
type DefaultError struct {
	// Error code
	Code float64 `json:"code,omitempty"`
	// Error message
	Error_ string `json:"error,omitempty"`
	// Error source
	Source string `json:"source,omitempty"`
}
