/*
 * Keep Charged
 *
 * API documentation
 *
 * API version: 0.0.1 beta
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StationIdBody struct {

	Data *Object `json:"data,omitempty"`
}
