/*
 * Keep Charged
 *
 * API documentation
 *
 * API version: 0.0.1 beta
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"ApiLogoutPut",
		strings.ToUpper("Put"),
		"/api/logout",
		ApiLogoutPut,
	},

	Route{
		"ApiNearestGet",
		strings.ToUpper("Get"),
		"/api/nearest",
		ApiNearestGet,
	},

	Route{
		"ApiPostExamplePost",
		strings.ToUpper("Post"),
		"/api/post_example",
		ApiPostExamplePost,
	},

	Route{
		"ApiStationIdGet",
		strings.ToUpper("Get"),
		"/api/station/{id}",
		ApiStationIdGet,
	},

	Route{
		"ApiStationsGet",
		strings.ToUpper("Get"),
		"/api/stations",
		ApiStationsGet,
	},

	Route{
		"Mobile8",
		strings.ToUpper("Put"),
		"/api/station/{id}",
		Mobile8,
	},

	Route{
		"Mobile9",
		strings.ToUpper("Delete"),
		"/api/station/{id}",
		Mobile9,
	},

	Route{
		"ApiLoginPut",
		strings.ToUpper("Put"),
		"/api/login",
		ApiLoginPut,
	},

	Route{
		"ApiRegisterPut",
		strings.ToUpper("Put"),
		"/api/register",
		ApiRegisterPut,
	},
}
